// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Amenity struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Attendance struct {
	ID           int32              `json:"id"`
	EmployeeID   pgtype.Text        `json:"employee_id"`
	BookingID    pgtype.Int4        `json:"booking_id"`
	CheckInTime  pgtype.Timestamptz `json:"check_in_time"`
	CheckOutTime pgtype.Timestamptz `json:"check_out_time"`
	Duration     pgtype.Time        `json:"duration"`
}

type AuditLog struct {
	ID        int32              `json:"id"`
	TableName string             `json:"table_name"`
	RecordID  string             `json:"record_id"`
	Action    string             `json:"action"`
	UserEmail pgtype.Text        `json:"user_email"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}

type Booking struct {
	ID         int32              `json:"id"`
	ResourceID pgtype.Int4        `json:"resource_id"`
	EmployeeID pgtype.Text        `json:"employee_id"`
	Date       pgtype.Date        `json:"date"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	Status     pgtype.Text        `json:"status"`
}

type BookingStatus struct {
	Status      string `json:"status"`
	Description string `json:"description"`
}

type Building struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Department struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Employee struct {
	EmployeeID   string      `json:"employee_id"`
	DepartmentID pgtype.Int4 `json:"department_id"`
	TeamID       pgtype.Int4 `json:"team_id"`
}

type Floor struct {
	ID          int32  `json:"id"`
	FloorNumber int32  `json:"floor_number"`
	FloorPlan   string `json:"floor_plan"`
	BuildingID  int32  `json:"building_id"`
}

type Permission struct {
	Permission  string `json:"permission"`
	Description string `json:"description"`
}

type Resource struct {
	ID           int32  `json:"id"`
	FloorID      int32  `json:"floor_id"`
	ZoneID       string `json:"zone_id"`
	ResourceType string `json:"resource_type"`
	Identifier   string `json:"identifier"`
	Capacity     int32  `json:"capacity"`
	Status       string `json:"status"`
}

type ResourceAmenity struct {
	ResourceID int32  `json:"resource_id"`
	AmenityID  string `json:"amenity_id"`
}

type ResourceStatus struct {
	Status      string `json:"status"`
	Description string `json:"description"`
}

type Role struct {
	Role        string `json:"role"`
	Description string `json:"description"`
}

type RolePermission struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

type Team struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	Description  string      `json:"description"`
	DepartmentID pgtype.Int4 `json:"department_id"`
}

type User struct {
	Email      string      `json:"email"`
	Name       string      `json:"name"`
	EmployeeID pgtype.Text `json:"employee_id"`
}

type UserRole struct {
	UserEmail string `json:"user_email"`
	Role      string `json:"role"`
}

type Zone struct {
	ID           string `json:"id"`
	FloorID      int32  `json:"floor_id"`
	DepartmentID int32  `json:"department_id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
}
