CREATE TABLE "buildings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" varchar NOT NULL
);

CREATE TABLE "floors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "floor_number" integer NOT NULL,
  "floor_plan" varchar NOT NULL,
  "building_id" integer NOT NULL
);

CREATE TABLE "zones" (
  "id" varchar PRIMARY KEY,
  "floor_id" integer NOT NULL,
  "department_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL
);

CREATE TABLE "resource_status" (
  "status" varchar PRIMARY KEY,
  "description" varchar NOT NULL
);

CREATE TABLE "resources" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "floor_id" integer NOT NULL,
  "zone_id" varchar NOT NULL,
  "resource_type" varchar NOT NULL,
  "identifier" varchar UNIQUE NOT NULL,
  "capacity" integer NOT NULL,
  "status" varchar NOT NULL
);

CREATE TABLE "amenities" (
  "id" varchar PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" varchar NOT NULL
);

CREATE TABLE "resource_amenities" (
  "resource_id" integer NOT NULL,
  "amenity_id" varchar NOT NULL,
  PRIMARY KEY ("resource_id", "amenity_id")
);

CREATE TABLE "departments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" varchar NOT NULL
);

CREATE TABLE "teams" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" varchar NOT NULL,
  "department_id" integer
);

CREATE TABLE "permissions" (
  "permission" varchar PRIMARY KEY,
  "description" varchar NOT NULL
);

CREATE TABLE "roles" (
  "role" varchar PRIMARY KEY,
  "description" varchar NOT NULL
);

CREATE TABLE "role_permissions" (
  "role_id" varchar,
  "permission_id" varchar,
  PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE "users" (
  "email" varchar PRIMARY KEY,
  "name" varchar NOT NULL,
  "employee_id" varchar UNIQUE
);

CREATE TABLE "user_roles" (
  "user_email" varchar,
  "role" varchar,
  PRIMARY KEY ("user_email", "role")
);

CREATE TABLE "employees" (
  "employee_id" varchar PRIMARY KEY,
  "department_id" integer,
  "team_id" integer
);

CREATE TABLE "booking_status" (
  "status" varchar PRIMARY KEY,
  "description" varchar NOT NULL
);

CREATE TABLE "bookings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "resource_id" integer,
  "employee_id" varchar,
  "date" date NOT NULL,
  "start_time" timestamptz NOT NULL,
  "end_time" timestamptz NOT NULL,
  "status" varchar
);

CREATE TABLE "attendances" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" varchar,
  "booking_id" integer,
  "check_in_time" timestamptz,
  "check_out_time" timestamptz,
  "duration" time
);

CREATE TABLE "audit_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_name" varchar NOT NULL,
  "record_id" text NOT NULL,
  "action" varchar NOT NULL,
  "user_email" varchar,
  "timestamp" timestamptz DEFAULT (now())
);

CREATE INDEX "idx_floor_building_number" ON "floors" ("building_id", "floor_number");

CREATE INDEX "idx_zone_floor_name" ON "zones" ("floor_id", "name");

CREATE INDEX "idx_zone_department" ON "zones" ("department_id");

CREATE INDEX "idx_resource_floor" ON "resources" ("floor_id");

CREATE INDEX "idx_resource_zone" ON "resources" ("zone_id");

CREATE INDEX "idx_resource_type_status" ON "resources" ("resource_type", "status");

CREATE INDEX "idx_resource_status" ON "resources" ("status");

CREATE INDEX "idx_team_department" ON "teams" ("department_id");

CREATE INDEX "idx_employee_department" ON "employees" ("department_id");

CREATE INDEX "idx_employee_team" ON "employees" ("team_id");

CREATE INDEX "idx_employee_dept_team" ON "employees" ("department_id", "team_id");

CREATE INDEX "idx_booking_resource_date" ON "bookings" USING BRIN ("resource_id", "date");

CREATE INDEX "idx_booking_timespan" ON "bookings" ("resource_id", "start_time", "end_time");

CREATE INDEX "idx_booking_employee_date" ON "bookings" ("employee_id", "date");

CREATE INDEX "idx_booking_status" ON "bookings" ("status");

CREATE INDEX "idx_booking_date" ON "bookings" USING BRIN ("date");

CREATE INDEX "idx_attendance_booking" ON "attendances" ("booking_id");

CREATE INDEX "idx_attendance_emp_checkin" ON "attendances" ("employee_id", "check_in_time");

CREATE INDEX "idx_attendance_checkin" ON "attendances" USING BRIN ("check_in_time");

CREATE INDEX "idx_audit_table_record" ON "audit_log" ("table_name", "record_id");

CREATE INDEX "idx_audit_user_temporal" ON "audit_log" ("user_email", "timestamp");

CREATE INDEX "idx_audit_time" ON "audit_log" USING BRIN ("timestamp");

ALTER TABLE "floors" ADD FOREIGN KEY ("building_id") REFERENCES "buildings" ("id");

ALTER TABLE "zones" ADD FOREIGN KEY ("floor_id") REFERENCES "floors" ("id");

ALTER TABLE "zones" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");

ALTER TABLE "resources" ADD FOREIGN KEY ("floor_id") REFERENCES "floors" ("id");

ALTER TABLE "resources" ADD FOREIGN KEY ("zone_id") REFERENCES "zones" ("id");

ALTER TABLE "resources" ADD FOREIGN KEY ("status") REFERENCES "resource_status" ("status");

ALTER TABLE "resource_amenities" ADD FOREIGN KEY ("resource_id") REFERENCES "resources" ("id");

ALTER TABLE "resource_amenities" ADD FOREIGN KEY ("amenity_id") REFERENCES "amenities" ("id");

ALTER TABLE "teams" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("permission");

ALTER TABLE "users" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_email") REFERENCES "users" ("email");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role") REFERENCES "roles" ("role");

ALTER TABLE "employees" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");

ALTER TABLE "employees" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("resource_id") REFERENCES "resources" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("status") REFERENCES "booking_status" ("status");

ALTER TABLE "attendances" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "attendances" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id");

ALTER TABLE "audit_log" ADD FOREIGN KEY ("user_email") REFERENCES "users" ("email");
